export const AUTH_TOKEN_KEY = 'auth_token'
export const ACCESS_TOKEN_KEY = 'access_token'
export const REFRESH_TOKEN_KEY = 'refresh_token'
export const USER_KEY = 'user'
export const AUTH_USER_KEY = 'auth_user'